name: PR PDF Preview

on:
  pull_request:

jobs:
  build-pdf-preview:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Remove previous sample project
        run: rm -rf fairy-dust-sprinkling-made-easy

      - name: Generate sample book project
        run: npm run write -- new "Fairy Dust Sprinkling Made Easy"

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: fairy-dust-sprinkling-made-easy
          root_file: main.tex

      - name: Rename PDF with commit SHA
        run: >
          mv
          fairy-dust-sprinkling-made-easy/main.pdf
          fairy-dust-sprinkling-made-easy/fairy-dust-sprinkling-made-easy-${GITHUB_SHA}.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: fairy-dust-sprinkling-made-easy-pdf-${{ github.sha }}
          path: fairy-dust-sprinkling-made-easy/fairy-dust-sprinkling-made-easy-${{ github.sha }}.pdf
          compression-level: 0
